
-- Insert 10 more sample events with South African locations and different organizers
INSERT INTO public.events (
  title,
  description,
  date,
  time,
  venue,
  address,
  category,
  price,
  image_url,
  max_attendees,
  current_attendees,
  organizer_id,
  tags,
  is_active
) VALUES 
(
  'Cape Town Jazz Festival 2024',
  'Experience the magic of jazz with world-renowned artists and local talent in the beautiful Mother City. Three days of non-stop music, food, and culture.',
  '2024-09-15',
  '18:00',
  'Cape Town International Convention Centre',
  '1 Lower Long Street, Cape Town, 8001, South Africa',
  'Music',
  350.00,
  'https://images.unsplash.com/photo-1461749280684-dccba630e2f6',
  3000,
  1250,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['jazz', 'music', 'festival', 'cape town'],
  true
),
(
  'Johannesburg Tech Summit',
  'Africas premier technology conference bringing together innovators, entrepreneurs, and thought leaders to shape the future of tech on the continent.',
  '2024-08-28',
  '08:30',
  'Sandton Convention Centre',
  '161 Maude Street, Sandton, Johannesburg, 2196, South Africa',
  'Technology',
  450.00,
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
  800,
  456,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['technology', 'innovation', 'africa', 'networking'],
  true
),
(
  'Durban Curry Festival',
  'Celebrate the rich culinary heritage of Durban with authentic Indian cuisine, cooking demonstrations, and cultural performances.',
  '2024-09-05',
  '11:00',
  'Moses Mabhida Stadium Precinct',
  '44 Isaiah Ntshangase Road, Durban, 4001, South Africa',
  'Food & Drink',
  85.00,
  'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
  1200,
  678,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['food', 'curry', 'indian', 'durban', 'culture'],
  true
),
(
  'Stellenbosch Wine & Business Network',
  'Connect with fellow entrepreneurs while enjoying world-class wines from the renowned Stellenbosch wine region.',
  '2024-08-20',
  '17:30',
  'Babylonstoren Wine Estate',
  'Klapmuts-Simondium Road, Stellenbosch, 7625, South Africa',
  'Business',
  280.00,
  'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7',
  150,
  89,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['wine', 'business', 'networking', 'stellenbosch'],
  true
),
(
  'Zeitz Contemporary Art Exhibition',
  'Explore cutting-edge contemporary African art at Africas largest museum of contemporary art.',
  '2024-09-10',
  '10:00',
  'Zeitz Museum of Contemporary African Art',
  'Silo District, V&A Waterfront, Cape Town, 8001, South Africa',
  'Arts & Culture',
  0.00,
  'https://images.unsplash.com/photo-1605810230434-7631ac76ec81',
  300,
  156,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['art', 'contemporary', 'african', 'free', 'museum'],
  true
),
(
  'Table Mountain Sunrise Yoga Retreat',
  'Start your day with mindful yoga practice as the sun rises over Table Mountain and Cape Town.',
  '2024-08-25',
  '05:30',
  'Table Mountain National Park',
  'Table Mountain, Cape Town, 8001, South Africa',
  'Health & Wellness',
  120.00,
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c',
  40,
  28,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['yoga', 'sunrise', 'table mountain', 'wellness'],
  true
),
(
  'Pretoria Digital Marketing Masterclass',
  'Learn advanced digital marketing strategies from South African industry experts and international speakers.',
  '2024-09-12',
  '09:00',
  'University of Pretoria Business School',
  'Hillcrest Campus, Lynnwood Road, Pretoria, 0002, South Africa',
  'Business',
  195.00,
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
  200,
  142,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['digital marketing', 'pretoria', 'masterclass', 'business'],
  true
),
(
  'Kruger Park Photography Safari',
  'Capture the Big Five and breathtaking landscapes with professional wildlife photographers as your guides.',
  '2024-08-30',
  '05:00',
  'Kruger National Park',
  'Kruger Park, Skukuza Rest Camp, Mpumalanga, 1350, South Africa',
  'Arts & Culture',
  850.00,
  'https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b',
  20,
  14,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['photography', 'safari', 'wildlife', 'kruger'],
  true
),
(
  'Port Elizabeth Surfing Championship',
  'Watch pro surfers compete in the annual championship at one of South Africas premier surfing destinations.',
  '2024-09-22',
  '07:00',
  'Pollock Beach',
  'Pollock Beach, Port Elizabeth, 6001, South Africa',
  'Sports',
  45.00,
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
  500,
  234,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['surfing', 'sports', 'championship', 'port elizabeth'],
  true
),
(
  'Bloemfontein Comedy Night',
  'Laugh out loud with South Africas funniest comedians performing their latest material in an intimate venue.',
  '2024-08-17',
  '20:00',
  'Sand du Plessis Theatre',
  '79 Markgraaff Street, Bloemfontein, 9301, South Africa',
  'Entertainment',
  75.00,
  'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9',
  180,
  98,
  (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1 OFFSET 0),
  ARRAY['comedy', 'entertainment', 'bloemfontein', 'south african'],
  true
);
