
-- Insert sample events for testing purposes
INSERT INTO public.events (
  title,
  description,
  date,
  time,
  venue,
  address,
  category,
  price,
  image_url,
  max_attendees,
  current_attendees,
  organizer_id,
  tags,
  is_active
) VALUES 
(
  'Summer Music Festival 2024',
  'Join us for an incredible day of live music featuring chart-topping artists, local bands, and emerging talent. Experience multiple stages, gourmet food trucks, craft beer gardens, and interactive art installations in a beautiful outdoor setting.',
  '2024-08-15',
  '14:00',
  'Central Park Amphitheater',
  '123 Park Avenue, New York, NY 10001',
  'Music',
  75.00,
  '/placeholder.svg',
  500,
  156,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['music', 'festival', 'outdoor', 'family'],
  true
),
(
  'AI & Machine Learning Summit',
  'Dive deep into the future of artificial intelligence with industry pioneers, researchers, and innovators. Network with leading AI professionals, attend hands-on workshops, and discover the latest breakthroughs in machine learning.',
  '2024-07-28',
  '09:00',
  'Innovation Tech Hub',
  '456 Innovation Street, San Francisco, CA 94105',
  'Technology',
  120.00,
  '/placeholder.svg',
  200,
  89,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['technology', 'AI', 'networking', 'professional'],
  true
),
(
  'Urban Food & Wine Experience',
  'Savor culinary masterpieces from award-winning chefs paired with premium wines from renowned vineyards. Enjoy live cooking demonstrations and wine tastings in an elegant rooftop setting.',
  '2024-08-05',
  '18:30',
  'Skyline Rooftop Venue',
  '789 Luxury Lane, Los Angeles, CA 90210',
  'Food & Drink',
  95.00,
  '/placeholder.svg',
  100,
  67,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['food', 'wine', 'tasting', 'luxury'],
  true
),
(
  'Startup Pitch Battle 2024',
  'Watch the next generation of entrepreneurs pitch their groundbreaking ideas to top-tier investors. Network with founders, investors, and industry experts.',
  '2024-08-02',
  '10:00',
  'Entrepreneur Hub',
  '321 Startup Street, Austin, TX 78701',
  'Business',
  25.00,
  '/placeholder.svg',
  150,
  98,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['startup', 'business', 'networking', 'competition'],
  true
),
(
  'Contemporary Art Showcase',
  'Discover cutting-edge contemporary art from emerging and established artists. Meet the artists, participate in guided tours, and enjoy an exclusive wine reception.',
  '2024-08-10',
  '19:00',
  'Modern Art Gallery District',
  '654 Arts District, Chicago, IL 60601',
  'Arts & Culture',
  0.00,
  '/placeholder.svg',
  120,
  43,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['art', 'gallery', 'culture', 'free'],
  true
),
(
  'Wellness & Mindfulness Retreat',
  'Rejuvenate your mind, body, and spirit with expert-led yoga sessions, guided meditation, and holistic wellness practices. Includes healthy meals and spa treatments.',
  '2024-08-18',
  '08:00',
  'Serenity Wellness Sanctuary',
  '987 Peaceful Path, Sedona, AZ 86336',
  'Health & Wellness',
  180.00,
  '/placeholder.svg',
  40,
  28,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['yoga', 'wellness', 'meditation', 'retreat'],
  true
),
(
  'Digital Marketing Conference',
  'Learn the latest digital marketing strategies from industry experts. Sessions cover social media, SEO, content marketing, and emerging trends.',
  '2024-07-25',
  '09:30',
  'Convention Center West',
  '555 Business Blvd, Denver, CO 80202',
  'Business',
  85.00,
  '/placeholder.svg',
  250,
  134,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['marketing', 'digital', 'conference', 'business'],
  true
),
(
  'Outdoor Photography Workshop',
  'Master landscape and nature photography with professional photographers. Includes equipment demos and hands-on shooting in scenic locations.',
  '2024-08-12',
  '07:00',
  'Mountain View Trail Head',
  '123 Nature Trail, Boulder, CO 80301',
  'Arts & Culture',
  65.00,
  '/placeholder.svg',
  25,
  18,
  (SELECT id FROM public.profiles LIMIT 1),
  ARRAY['photography', 'workshop', 'outdoor', 'nature'],
  true
);
