
-- Insert sample events to populate the homepage
INSERT INTO public.events (
  title,
  description,
  date,
  time,
  venue,
  address,
  category,
  price,
  image_url,
  max_attendees,
  current_attendees,
  is_active,
  tags
) VALUES 
(
  'Summer Music Festival 2024',
  'Join us for an amazing day of live music featuring local and international artists. Food trucks, craft beer, and family-friendly activities.',
  '2024-08-15',
  '14:00',
  'Central Park Amphitheater',
  '123 Park Avenue, New York, NY 10001',
  'Music',
  75.00,
  '/placeholder.svg',
  500,
  156,
  true,
  ARRAY['music', 'festival', 'outdoor', 'family']
),
(
  'Tech Innovation Summit',
  'Discover the latest trends in AI, blockchain, and emerging technologies. Network with industry leaders and innovators.',
  '2024-07-28',
  '09:00',
  'Convention Center',
  '456 Tech Boulevard, San Francisco, CA 94105',
  'Technology',
  120.00,
  '/placeholder.svg',
  200,
  89,
  true,
  ARRAY['technology', 'AI', 'networking', 'professional']
),
(
  'Food & Wine Tasting',
  'Experience culinary delights from renowned chefs paired with premium wines from around the world.',
  '2024-08-05',
  '18:00',
  'Grand Ballroom Hotel',
  '789 Luxury Lane, Los Angeles, CA 90210',
  'Food & Drink',
  95.00,
  '/placeholder.svg',
  100,
  67,
  true,
  ARRAY['food', 'wine', 'tasting', 'luxury']
),
(
  'Startup Pitch Competition',
  'Watch emerging startups pitch their innovative ideas to top investors. Network with entrepreneurs and VCs.',
  '2024-07-22',
  '10:00',
  'Innovation Hub',
  '321 Startup Street, Austin, TX 78701',
  'Business',
  25.00,
  '/placeholder.svg',
  150,
  98,
  true,
  ARRAY['startup', 'business', 'networking', 'competition']
),
(
  'Art Gallery Opening',
  'Discover contemporary art from local and international artists. Wine reception and artist meet & greet.',
  '2024-08-10',
  '19:00',
  'Modern Art Gallery',
  '654 Arts District, Chicago, IL 60601',
  'Arts & Culture',
  0.00,
  '/placeholder.svg',
  80,
  23,
  true,
  ARRAY['art', 'gallery', 'culture', 'free']
),
(
  'Yoga & Wellness Retreat',
  'Rejuvenate your mind and body with yoga sessions, meditation, and wellness workshops in a peaceful setting.',
  '2024-08-20',
  '08:00',
  'Serenity Wellness Center',
  '987 Peaceful Path, Sedona, AZ 86336',
  'Health & Wellness',
  150.00,
  '/placeholder.svg',
  40,
  28,
  true,
  ARRAY['yoga', 'wellness', 'meditation', 'retreat']
);
