// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { SUPABASE_CONFIG } from "@/lib/secureConstants";

// Use secure configuration from constants
const SUPABASE_URL = SUPABASE_CONFIG.URL;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_CONFIG.ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Supabase client instance, typed with your Database schema.
 */
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);